let data = [{
    "id": 1,
    "nombre": "Cleopatra",
    "apellido": "Farries",
    "email": "cfarries0@cnet.com",
    "gender": "Female",
    "edad": 51
  }, {
    "id": 2,
    "nombre": "Belle",
    "apellido": "Shier",
    "email": "bshier1@webnode.com",
    "gender": "Female",
    "edad": 25
  }, {
    "id": 3,
    "nombre": "Emlyn",
    "apellido": "Tomkys",
    "email": "etomkys2@pen.io",
    "gender": "Male",
    "edad": 72
  }, {
    "id": 4,
    "nombre": "Marion",
    "apellido": "Broughton",
    "email": "mbroughton3@github.com",
    "gender": "Male",
    "edad": 45
  }, {
    "id": 5,
    "nombre": "Debbi",
    "apellido": "Gollin",
    "email": "dgollin4@typepad.com",
    "gender": "Female",
    "edad": 11
  }, {
    "id": 6,
    "nombre": "Bryon",
    "apellido": "Ogbourne",
    "email": "bogbourne5@npr.org",
    "gender": "Male",
    "edad": 59
  }, {
    "id": 7,
    "nombre": "Leola",
    "apellido": "Dowers",
    "email": "ldowers6@lycos.com",
    "gender": "Female",
    "edad": 38
  }, {
    "id": 8,
    "nombre": "Saudra",
    "apellido": "Houseley",
    "email": "shouseley7@51.la",
    "gender": "Female",
    "edad": 19
  }, {
    "id": 9,
    "nombre": "Kippy",
    "apellido": "Seagrave",
    "email": "kseagrave8@mediafire.com",
    "gender": "Female",
    "edad": 70
  }, {
    "id": 10,
    "nombre": "Ginny",
    "apellido": "Trussman",
    "email": "gtrussman9@disqus.com",
    "gender": "Female",
    "edad": 24
  }, {
    "id": 11,
    "nombre": "Persis",
    "apellido": "Cordeix",
    "email": "pcordeixa@123-reg.co.uk",
    "gender": "Female",
    "edad": 43
  }, {
    "id": 12,
    "nombre": "Gregor",
    "apellido": "Anglin",
    "email": "ganglinb@a8.net",
    "gender": "Male",
    "edad": 52
  }, {
    "id": 13,
    "nombre": "Eleonora",
    "apellido": "Coleford",
    "email": "ecolefordc@foxnews.com",
    "gender": "Female",
    "edad": 90
  }, {
    "id": 14,
    "nombre": "Eleonore",
    "apellido": "Espadas",
    "email": "eespadasd@google.ru",
    "gender": "Female",
    "edad": 66
  }, {
    "id": 15,
    "nombre": "Prentice",
    "apellido": "Gerriet",
    "email": "pgerriete@nbcnews.com",
    "gender": "Male",
    "edad": 9
  }];
$(document).ready(function(){
    localStorage.setItem("personas", JSON.stringify(data));
    Helpers.TableHelper.CreateTable(CRUD.PersonaCRUD.GetAll());
    
});